### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by OutofRange-Nico** [MCMi460/3DS-RPC#2]
There are no releases to download. Can you provide a release or say the steps that are nesesarry to run this?

**Comment by MCMi460** [comment]
Currently, it's not exactly ready for the public (I'm planning on creating a GUI for the client next weekend as well as finishing up/polishing and appending features to the network section), but I'll post some basic instructions for using the client.
*(I also can't publish any Windows releases until my new computer comes in next week.)*

## Running the CLI
Firstly, the server that is running 3DS-RPC will always be based off of the main branch, so you should download the client from there.
Secondly, using the program is as simple as installing the requirements and running the `client.py`.
For Windows:
```bat
cd .\client
py -m pip install -r requirements.txt
py client.py
```
macOS/Linux:
```sh
cd ./client
python3 -m pip install -r requirements.txt
python3 client.py
```
---
I will keep this issue open until I have either released some products or published a proper guide to using the app.

**Comment by OutofRange-Nico** [comment]
Thanks you for the basic instructions. I look forward to this project.

**Comment by MCMi460** [comment]
Building is now available for macOS (via a `build.sh` script -> d41486b47add4962c06d8ca46de837b292656563), although the GUI is barebones, at best. I will include a building script for Windows sometime soon, then release a v1.0. Be warned, however. The GUI is not intended to be very complicated.

---
### What's with the GUI?
Instead of an in-depth GUI in the app, I'm going to include a button on the system-tray app (which is all that GUI currently is) that will send the user to the website. That is where they can see more information about their user and other fun stuff.
I may also include a configurable settings page for changing some minor presence things, but past that, I have no intention for doing much with the GUI (mostly because I'm tired as hell with this project).

---
### Minor Update
A minor update for the project, as well, is that I've given up on my big dreams for a large friends network via the website (as seen with 2d1ad3737869dfbe5dc020b496a97cf745c5f6d9). **That means a release for the client may come very soon.**

**Comment by MCMi460** [comment]
Releases for macOS and Windows should be released later today.
