### ISSUE TITLE
User profile not being created

### ISSUE THREAD

**Issue by Beamy68** [MCMi460/3DS-RPC#20]
My user profile is not showing up on the site. It has been a day since I have signed up, and the console shows up in my list, but does not do any rich presence.

**Comment by MCMi460** [comment]
Ah, it is very likely that we've hit the threshold again for queue times.
The account creation should take place on the next time the queue hits your position, so long as it is before ten minutes after account creation. However, if the queue grows long enough that each full cycle takes over ten minutes, then a good amount of the time, new accounts will never be finished in creation because the bot can't get to it in time.
I'll extend the creation delay to be longer than ten minutes, but this marks the lengthening of the queue to be over ten minutes, I suppose.

**Comment by MCMi460** [comment]
(As a side note, if I had enough money to afford a second 3DS, I could make a second bot account for a second queue. I am considering opening a Patreon, as I do not have a disposable income of my own at the moment.)

**Comment by MCMi460** [comment]
I've updated the server. For now, I suggest registering your 3DS friendcode again. Hopefully this time, it will work.
Thanks for your patience!

**Comment by Beamy68** [comment]
Hello! I re-registered my 3DS friend code, and it still seems to not be working. I'm unsure what is causing this bug either, but the spot in the consoles list where I should be able to click to a profile doesn't say anything. 
![image](https://github.com/MCMi460/3DS-RPC/assets/31512954/e0e9c8a1-1ba9-45cd-b16f-61b999fde411)

**Comment by Beamy68** [comment]
My status is now showing up on discord! However, there is still no profile on the website...
![image](https://github.com/MCMi460/3DS-RPC/assets/31512954/5e26b277-8810-4847-a690-2b6a6a679744)
![image](https://github.com/MCMi460/3DS-RPC/assets/31512954/c5d76129-8da8-4928-9e9f-0674ba09ad87)

**Comment by MCMi460** [comment]
While the two leading zeroes most certainly scare me, I think that it's more likely that your 3DS' status ends with a trailing space. Is this the case?

**Comment by Beamy68** [comment]
It does, however I haven't changed it since I got my 3DS, so I did not realize. I'll fix it.

**Comment by Beamy68** [comment]
Would it also be possible to upgrade the servers using 2dses? You can find them for pretty low prices.

**Comment by MCMi460** [comment]
> It does, however I haven't changed it since I got my 3DS, so I did not realize. I'll fix it.
> 
> (That fixed the issue, thanks!)

The reason why can be found here: https://github.com/MCMi460/3DS-RPC/blob/main/TERMS.md

> Would it also be possible to upgrade the servers using 2dses? You can find them for pretty low prices.

They can be! But the problem is that I am greatly broke and cannot afford new 2DSes. Since I don't have a source of income, I unfortunately can't afford any new ones at the moment, but once I can, then I'll set up a "queue" system where you can choose to register your console with one of the available queues. Estimated wait times per update will be provided there, as well.
Also, broken 3DS/2DSes work as well, but they need to be:
- 3DS or 2DS family
- Able to connect to the internet, register an NNID, etc
- Able to be hacked
- That's pretty much it. I'd probably factory reset it first, but I really just need to hack it, install an SSL patch (<https://github.com/SciresM/3DS-SSL-Patch>), run this https://9net.org/~stary/get_3ds_pid_password.3dsx to get my keys, connect it to my proxy, open the friends app (kinda optional), sniff its traffic, then BAM. I can pretty much throw it away.
