### ISSUE TITLE
[Unrelated Question] activities.write scope

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [MCMi460/3DS-RPC#46]
Hey,

Just a simple question.
How did you unlock the `activities.write` OAUTH2 scope?

I want to make an application on my own and both the API docs, as well as the discord dev support itself say it is impossible to use.

**Comment by spotlightishere** [comment]
Hey there! We reached out to Discord's developer support and requested access. Regretfully it appears they have since become far more strict on who gains approval - even some of our own developers, in an effort to help develop/test, have been denied approval.

Wishing you the best of luck in your efforts to try and gain access!

**Comment by ErdbeerbaerLP** [comment]
Funny thing is, the discord support told me it's not available for apps *at all*

Guess ima scrap my idea then

**Comment by HotaruBlaze** [comment]
Yeah, they no longer give it out at all, its a pretty stingy policy and makes discord a worse platform overall.
